version: '2.2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/src/
      - /src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://swapi@postgres/swapi
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: swapi
      POSTGRES_DB: swapi